#write out 5 example each of datatype example(integer,float,boolean,string and None.)
#string
password_name="JOYCE"
print(password_name)
phone_name="tecno"
print(phone_name)
name_of_textbook="English"
print(name_of_textbook)
city="lagos"
print(city)
phone_number="123456789"
print(phone_number)

#integer
number_of_song_listed=34
print(number_of_song_listed)
number_of_phone_in_class=23
print(number_of_phone_in_class)
number_of_subject=4
print(number_of_subject)
time_frame=89
print(time_frame)
number_class=78
print(number_class)

#float
percentage_ratio=3.4
print(percentage_ratio)
temperture=6.89
print(temperture)
password=3.56
print(password)
ratio_duration=56.7
print(ratio_duration)
weather_condtion=8.9
print(weather_condtion)

#boolean
is_password_correct=True
print(is_password_correct)
is_admin_in=True
print(is_admin_in)
logged_in=False
print(logged_in)
password=True
print(password)
checkmate=False
print(checkmate)

#none
working_experience=None
print(working_experience)
language_favourites=None
print(language_favourites)
pet_name=None
print(pet_name)
anime_dislikes=None
print(anime_dislikes)
colour_favourites=None
print(colour_favourites)